# Generated by Django 4.0.4 on 2022-06-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saida_de_mercadoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidamercadoria',
            name='validade_produto',
        ),
    ]
