# Generated by Django 4.0.4 on 2022-06-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saida_de_mercadoria', '0002_remove_saidamercadoria_validade_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaidaMercadoria',
        ),
    ]
