# Generated by Django 4.0.4 on 2022-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_saidamercadoria_entradamercadoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidamercadoria',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
    ]
